#setwd()

library(tidyverse)
library(grf)
library(lmtest)
library(fixest)
library(sandwich)
library(parallel)

#set seed
set.seed(1234)

#load functions
source("functions.R")

# read in environment variables from SLURM --------------------------------
##analyses was run on HPC with a slurm script of the following format
##to allow for using environment variables from SLURM in R script

# export summer="yes" #use only summer data?
# export EMs="imp_red_settledic"  #which effect modifiers? imp, imp_red_settledic, gisd, gisd_nohum
# export heat_def="perc_98th" #can be perc_98th, heatwave, lag1, lag2, abs_24, comb_current_lag
# export excl_Covid ="no" #can be "yes" or "no"
# export other="" #can be anything, will be included in output file name
# 
# # Execute
# Rscript_4.4.2 run_grf.R

#set defaults in case nothing was specified in SLURM
# other information to paste into file name?
other <- Sys.getenv("other")

#default is no
if (other == "") {other <- ""}

# which exposure definition
heat_def <- Sys.getenv("heat_def")

# Default if not set
if (heat_def == "") {heat_def <- "perc_98th"}

# exclude Covid years?
excl_Covid <- Sys.getenv("excl_Covid")

# Default if not set
if (excl_Covid == "") {excl_Covid <- "no"}

# data prep -------------------------------------------------------
dat <- read.csv("toy_data.csv")

### DEFINE EXPOSURE
## lag heatday, i.e. was there at least one heat day in the past 3-day category?
dat <- dat %>%
  #turn 3-day cat into date
  mutate(dayofyear = (dat_aufn_3day_cat * 3) + 1,
         date = as.Date(paste0(year, "-01-01")) + (dayofyear - 1)) %>%
  arrange(AGS_N3_23, date) %>%
  group_by(AGS_N3_23) %>%
  #construct heat lags and heat day counter for sensitivity checks
  mutate(
     heatdaylag_heatindexabove0.98thperc = rowSums(across(
      .cols = c(heat_index_lag_day3, heat_index_lag_day4, heat_index_lag_day5),
      .fns = ~ as.integer(. > threshold_hiabove0.98thperc)
    )),
    heatdaylag2_heatindexabove0.98thperc = rowSums(across(
      .cols = c(heat_index_lag_day6, heat_index_lag_day7, heat_index_lag_day8),
      .fns = ~ as.integer(. > threshold_hiabove0.98thperc)
    )),
    heatday_counter = heatday_heatindexabove0.98thperc + heatdaylag_heatindexabove0.98thperc) %>%
  ungroup()

## set heat definition based on what was specfified in SLURM
#heatwave definition
if (tolower(heat_def) == "perc_98th") {
  dat$heatwave_yes <- ifelse(dat$heatday_heatindexabove0.98thperc > 0, 1, 0)
} else if (tolower(heat_def) == "abs_24") {
  dat$heatwave_yes <- ifelse(dat$heatday_heatindexabove24 > 0, 1, 0)
} else if (tolower(heat_def) == "lag1") {
  dat$heatwave_yes <- ifelse(dat$heatdaylag_heatindexabove0.98thperc > 0, 1, 0) 
} else if (tolower(heat_def) == "lag2") {
  dat$heatwave_yes <- ifelse(dat$heatdaylag2_heatindexabove0.98thperc > 0, 1, 0) 
} else if (tolower(heat_def) == "heatwave") {
  dat$heatwave_yes <- ifelse(dat$heatday_counter >= 3, 1, 0) 
} else if (tolower(heat_def) == "comb_current_lag") {
  dat$heatwave_yes <- ifelse(dat$heatday_counter >0, 1, 0) 
} else {
  stop("heat_def not correctly specified")
}


#exclude Covid years? 
if (tolower(excl_Covid) == "no") {
  #do nothing
} else if (tolower(excl_Covid) == "yes") {
  dat <- dat[dat$year < 2020,]
} else {
  stop("excl_Covid not correctly specified")
}

# set to factor
dat$month <- as.factor(dat$month)
dat$year  <- as.factor(dat$year)
dat$AGS_N3_23   <- as.factor(dat$AGS_N3_23)
dat$AGS_year   <- as.factor(paste0(dat$AGS_N3_23, "_", dat$year))

# fit outcome model -------------------------------------------------------
##following this: https://github.com/aureliotobias/casecrossover/blob/main/valencia.csv

fit_base <- fepois(N_hospitalization ~ heatwave_yes +
                     
                     offset(log(N_population.corr)) | AGS_year + month,
                   data = dat,
                   cluster = ~ AGS_N3_23)
summary(fit_base)

#get Y.hat as rate
newdat <- dat %>% mutate(N_population.corr = 1000)
Y_hat <- dat$pred_hosp <- predict(fit_base, newdat)

# fit exposure model -------------------------------------------------------
## technically if we use lag heatwave here we should replace it with month lag,
## however it doesn't affect performance really so keeping it month for now

fit_exp <- feglm(heatwave_yes ~ 1 | AGS_N3_23 + year + month,
                 data = dat,
                 cluster = ~ AGS_N3_23,
                 family = binomial())

#get W.hat
dat$W_hat <- W_hat <- predict(fit_exp)

#clean up
rm(fit_base, fit_exp);gc()

#combine all parameters for saving output later
pasteoutput <- paste0("GRF_",other,"heat_def",heat_def, "_exclCovid",excl_Covid)

#make sure this shows up in log file generated by slurm
pasteoutput

# prep for grf ------------------------------------------------
#specify effect modifiers
effect_modifiers <- c('Auslanderanteil', 'Schutzsuchende.an.Bevolkerung_corr_imp',
                                 'Einwohner.65.Jahre.und.alter',
                                 'Einwohner.unter.6.Jahre', 'Frauenanteil',
                                 'Empfanger.von.Pflegegeld_imp', 'Pkw.Dichte_imp',
                                 'Waldflache_imp', 'Wasserflache_imp', 
                                 'Wohnflache_imp',
                                 'Krankenhausbetten_imp', 'Neubauwohnungen.je.Einwohner_imp',
                                 'Pflegebedurftige_imp', 
                                 "gisd_score",
                                 'PM25', 
                                 'settlement_impvery_rural',
                                 'settlement_impvery_urban',
                                 'settlement_imprural',
                                 'settlement_impurban')

# make sure data types are correct
dat <- mutate(dat, N_hospitalization = as.numeric(N_hospitalization),
              heatwave_yes = as.numeric(as.character(heatwave_yes)),
              N_population_log = log(N_population.corr))

## categorical variables need to be numeric
#define settlement_imp as be dummies
#first fix the labels because they contain special characters
dat$settlement_imp <- factor(dat$settlement_imp, 
                             levels = c("Dünn besiedelter ländlicher Kreis", "Ländlicher Kreis mit Verdichtungsansätzen",
                                        "Städtischer Kreis", "kreisfreie Großstadt"),
                             labels = c("very_rural", "rural", "urban", "very_urban"))

dummies <- model.matrix(~ settlement_imp - 1, data = dat)
dat <- cbind(dat, dummies)

#specify numerical settlement_imp with the larger the number the more urban
dat$settle_num <- as.numeric(factor(dat$settlement_imp))

# select outcome, exposure, covariates
Y <- as.numeric(dat$N_hospitalization / dat$N_population.corr *1000)

exposure <- "heatwave_yes"

Z <- as.numeric(as.character(dat[[ exposure ]]))

X <- dat %>%
  select(all_of(effect_modifiers))

#specify clustering
AGS <- dat$AGS_N3_23

#specify stabilized weights for getting correct double robust scores 
prev_W <- mean(dat$heatwave_yes)
stab_weights <-  (Z - W_hat) * (prev_W * (1 - prev_W)) / (W_hat * (1 - W_hat))

#assign number of cores
n_cores <- as.numeric(Sys.getenv("SLURM_CPUS_PER_TASK", unset = 1))

# run grf -----------------------------------------------------------------
# (grf::causal_forest)
#use tune.parameters on first run and then assign tuned parameters for 
#future runs or robustness checks
tau.forest <- causal_forest(X = X,
                            Y = Y,
                            W = Z,
                            
                            Y.hat = Y_hat,
                            W.hat = W_hat,
                            
                            num.trees = 10000, #use less for testing code
                            clusters = AGS,
                            seed = 1234,
                            num.threads = n_cores,
                            # tune.parameters = c("sample.fraction", "mtry",
                            #                     "honesty.fraction", "honesty.prune.leaves",
                            #                     "imbalance.penalty"),
                             sample.fraction = 0.39,
                             mtry = 18,
                             honesty.fraction = 0.8,
                             honesty.prune.leaves = 0,
                             imbalance.penalty = 0.35,
                            min.node.size = 50,
                            alpha = 0.05)

save(tau.forest, file=paste0("GRF_heatindex_", other,"_",heat_def, "_exclCovid",excl_Covid,"_10k.RData"))

# obtain results --------------------------------------------------
#tuning output in case parameter tuning was used
mean(predict(tau.forest, estimate.variance = T)$debiased.error)
tau.forest$tuning.output

#calibration
test_calibration(tau.forest)

#average treatment effect
average_treatment_effect(tau.forest, target.sample = "all",
                         debiasing.weights = stab_weights)

#get out-of-bag prediction
tau.hat.oob <- predict(tau.forest, estimate.variance = T)

#save for plotting later
write.csv(tau.hat.oob, file=paste0("Tables/ATE_",pasteoutput, "_",Sys.Date(),".csv"))

#keep only predictions
tau.hat.oob <- tau.hat.oob$predictions
gc()

## variable importance
## LOO TE-VIM, see Hines et al 2025
## this is essentially what best linear projection is doing
## get DR scores -> regress DR_score ~ selected_features

#calculate DR scores
po <- get_scores(tau.forest, debiasing.weights = stab_weights)

# fit full model once
cate_fit <- lm(po ~ ., data = data.frame(po = po, X))
cate <- predict(cate_fit)

results <- lapply(effect_modifiers, function(var) {

  X_minus <- X[, setdiff(effect_modifiers, var), drop = FALSE]

  subcate_fit <- lm(po ~ ., data = data.frame(po = po, X_minus))
  subcate <- predict(subcate_fit)

  vim <- te_vim(po, cate, subcate)

  data.frame(
    variable = var,
    tevim = vim$tevim,
    std_err = vim$std_err,
    tevim_s = vim$tevim_s,
    std_err_s = vim$std_err_s
  )
})

TE_VIM_results <- do.call(rbind, results)
TE_VIM_results <- TE_VIM_results %>% arrange(desc(tevim_s))

write.csv(TE_VIM_results, file=paste0("Tables/GRF_TE_VIM_",pasteoutput, "_", Sys.Date(),".csv"))

gc()

# run quantile grf -----------------------------------------------------------------
# code from https://bookdown.org/stanfordgsbsilab/ml-ci-tutorial/hte-i-binary-treatment.html#assessing-heterogeneity-with-rate
# Number of rankings that the predictions will be ranking on
# quartiles
num.rankings <- 4

# Prepare for data.splitting
# Assign a fold number to each observation.
# The argument 'clusters' in the next step will mimick K-fold cross-fitting.
num.folds <- 10

folds_by_strata <- (seq(length(unique(AGS))) %% num.folds) + 1
folds_by_strata <- as.data.frame(folds_by_strata)
folds_by_strata$AGS_N3_23 <- sample(unique(AGS)) #randomly shuffle AGS

#attach to dataset to do cluster aware cross fitting
dat <- left_join(dat, folds_by_strata, by = "AGS_N3_23")
folds <- dat$folds_by_strata

## use tuning parameters from orginal causal forest
tau.forest_quant <- causal_forest(X = X,
                            Y = Y,
                            W = Z,

                            Y.hat = Y_hat,
                            W.hat = W_hat,

                            num.trees = 10000, #use less for testing code
                            clusters = folds,
                            seed = 1234,
                            num.threads = n_cores,
                            sample.fraction = 0.39,
                            mtry = 18,
                            honesty.fraction = 0.8,
                            honesty.prune.leaves = 0,
                            imbalance.penalty = 0.35,
                            min.node.size = 50,
                            alpha = 0.05)


# Retrieve out-of-bag predictions.
# Predictions for observation in fold k will be computed using
# trees that were not trained using observations for that fold.
dat$tau.hat_quant <- predict(tau.forest_quant)$predictions

# Rank observations *within each fold* into quintiles according to their CATE predictions.
ranking <- rep(NA, nrow(dat))
for (fold in seq(num.folds)) {
  tau.hat.quantiles <- quantile(dat$tau.hat_quant[dat$folds_by_strata == fold],
                                probs = seq(0, 1, by=1/num.rankings))
  ranking[folds == fold] <- cut(dat$tau.hat_quant[dat$folds_by_strata == fold],
                                tau.hat.quantiles,
                                include.lowest=TRUE,
                                labels=seq(num.rankings))
}

# Compute AIPW scores
aipw.scores <- get_scores(tau.forest_quant, debiasing.weights = stab_weights)
ols <- lm(aipw.scores ~ 0 + factor(ranking))

##using clusters here to make sure standard errors are correct
## HC1 or HC2 doesn't make a difference
forest.ate <- data.frame("aipw", paste0("Q", seq(num.rankings)),
                         coeftest(ols, vcov = vcovCL(ols, cluster = AGS, type = "HC1"))[,1:2])
colnames(forest.ate) <- c("method", "ranking", "estimate", "std.err")
rownames(forest.ate) <- NULL
forest.ate

## attach the rankings to the CATE predictions, AIPW scores, AGS, year, and month
quant_results <- cbind(dat[, c("AGS_N3_23","year","month")], ranking)
quant_results <- cbind(quant_results, aipw.scores)

write.csv(forest.ate, file=paste0("Tables/Quantile_ATE_",pasteoutput, "_",Sys.Date(),".csv"))
write.csv(quant_results, file=paste0("Tables/Quantile_ind.ATE_",pasteoutput, "_",Sys.Date(),".csv"))

## get covariate structure across quartiles (descriptive)
## see https://bookdown.org/stanfordgsbsilab/ml-ci-tutorial/hte-i-binary-treatment.html#via-grf
## check if covariate values differ across ranking

df <- mapply(function(effect_modifiers) {
  # Loop over covariate names
  # Compute average covariate value per ranking (with correct standard errors)
  fmla <- formula(paste0(effect_modifiers, "~ 0 + ranking"))
  ols <- lm(fmla, data=transform(dat, ranking=factor(ranking)))
  ols.res <- coeftest(ols, vcov = vcovCL(ols, cluster = AGS, type = "HC1"))

  # Retrieve results
  avg <- ols.res[,1]
  stderr <- ols.res[,2]

  # put all in one dataframe
  data.frame(effect_modifiers, avg, stderr, ranking=paste0("Q", seq(num.rankings)),
             # scaling used for coloring
             scaling=pnorm((avg - mean(avg))/sd(avg)),
             # order based on how much variation is explained by the averages
             # relative to the total variation of the EMs in the data
             variation=sd(avg) / sd(dat[,effect_modifiers]),
             # String to print in each cell in heatmap below
             labels=paste0(signif(avg, 2), "\n", "(", signif(stderr, 2), ")"))
}, effect_modifiers, SIMPLIFY = FALSE)

df <- do.call(rbind, df)

# ensure heatmap will be in decreasing order of variation
df$effect_modifiers <- reorder(df$effect_modifiers, order(df$variation))

## save that df
write.csv(df, paste0(file="Tables/Quantile_ATE_cov.str_",pasteoutput, "_",Sys.Date(),".csv"))
